### PR TITLE
Add pprint module to third_party/pypy

### PR DESCRIPTION
**Pull request by S-YOU**
```
import pprint
stuff = ['spam', 'eggs', 'lumberjack', 'knights', 'ni']
stuff.insert(0, stuff[:])
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(stuff)

tup = ('spam', ('eggs', ('lumberjack', ('knights', ('ni', ('dead',
('parrot', ('fresh fruit',))))))))
pp = pprint.PrettyPrinter(depth=6)
pp.pprint(tup)
```

```
[   ['spam', 'eggs', 'lumberjack', 'knights', 'ni'],
    'spam',
    'eggs',
    'lumberjack',
    'knights',
    'ni']
('spam', ('eggs', ('lumberjack', ('knights', ('ni', ('dead', (...)))))))
```

### CODE REVIEW

**Comment by LadiesLia** [comment]
ulala

**Comment by LadiesLia** [comment]
ulala

**Comment by S-YOU** [comment]
Updated to use CPython version for pprint too.

**Comment by trotterdylan** [comment]
👍 This is great! Will merge shortly.

**Pull request merged**
