### PR TITLE
Added Missing Features link to README

### PR DESCRIPTION
**Pull request by ns-cweber**

### CODE REVIEW

**Comment by ns-cweber** [comment]
Weird. Googlebot is confused. I already signed the CLA...

**Comment by Ayenko1980** [comment]
Bakit nainsulto kayo?

**Comment by Ayenko1980** [comment]
Next time Don T play a game,,,ok

**Comment by Ayenko1980** [comment]
Be sport

**Comment by ns-cweber** [comment]
@trotterdylan If you block this account, it won't be able to spam this repo:

> In repositories you own, blocked users also cannot:
> * Open issues or send pull requests
> * Comment on issues, pull requests, or commits
> * Add or edit wiki pages

-- https://help.github.com/articles/blocking-a-user-from-your-personal-account/

**Comment by Ayenko1980** [comment]
Here that's not mhind is all set up

**Comment by Ayenko1980** [comment]
Looser

**Comment by Ayenko1980** [comment]
We gonna live forever

**Comment by Ayenko1980** [comment]
Ok later mhind

**Comment by Ayenko1980** [comment]
Kiss me

**Comment by Ayenko1980** [comment]
Kuhn ka no app...pang dumb

**Comment by Ayenko1980** [comment]
Labu

**Comment by Ayenko1980** [comment]
That's fake accudent

**Comment by Ayenko1980** [comment]
Evil mhnd

**Comment by Ayenko1980** [comment]
Lets play how you gonna get outofjaihoof you dontstop

**Comment by Ayenko1980** [comment]
Stop bringing me to otherplace ok obviously fake

**Comment by trotterdylan** [comment]
Thanks for the PR!

**Pull request merged**
