### PR TITLE
Add unittest module

### PR DESCRIPTION
**Pull request by S-YOU**
- Added unittest module
- File structure is different with CPython, because of relative import is not yet implemented.
- Also added os.path.basename
- `__doc__` is not always there, so commenting out from functtools wrapper
- Only added sequence helper, and sample tuple test.
- Still minimal working, need tuning

```
./run third_party/stdlib/test/test_tuple.py
test_constructors (__main__.TupleTest) ... ERROR
test_hash (__main__.TupleTest) ... ok
test_iadd (__main__.TupleTest) ... ok
test_imul (__main__.TupleTest) ... ok
test_len (__main__.TupleTest) ... ok
test_repr (__main__.TupleTest) ... ok
test_truth (__main__.TupleTest) ... ok
test_tupleresizebug (__main__.TupleTest) ... ok

======================================================================
ERROR: test_constructors (__main__.TupleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "third_party/stdlib/test/test_tuple.py", line 9, in test_constructors
    super(TupleTest, self).test_constructors()
  File "third_party/stdlib/test/seq_tests.py", line 136, in test_constructors
    self.assertEqual(self.type2test(g(s)), self.type2test(s))
  File "third_party/stdlib/test/seq_tests.py", line 21, in __getitem__
    return self.seqn[i]
TypeError: 'xrange' object has no attribute '__getitem__'

----------------------------------------------------------------------
Ran 8 tests in 0.438763s

FAILED (errors=1)
TestFailed: Traceback (most recent call last):
  File "third_party/stdlib/test/test_tuple.py", line 9, in test_constructors
    super(TupleTest, self).test_constructors()
  File "third_party/stdlib/test/seq_tests.py", line 136, in test_constructors
    self.assertEqual(self.type2test(g(s)), self.type2test(s))
  File "third_party/stdlib/test/seq_tests.py", line 21, in __getitem__
    return self.seqn[i]
TypeError: 'xrange' object has no attribute '__getitem__'
```

Note that above test error is because of xrange havn't implemented `__getitem__` yet.

### CODE REVIEW

**Comment by trotterdylan** [comment]
This is fantastic! Would you mind moving fnmatch to a separate PR?

**Comment by S-YOU** [comment]
unittest depends on it, but will do.

**Comment by S-YOU** [comment]
Done #141, will remove from this PR, once that is merged.

**Comment by S-YOU** [comment]
Rebased.

**Comment by S-YOU** [comment]
Let me remove one debugging codes, or may be in another PR.

**Comment by S-YOU** [comment]
Done

**Comment by S-YOU** [comment]
Hmm, rebase, rollback something, one more

**Comment by S-YOU** [comment]
Should be ok now.

**Pull request merged**
