### PR TITLE
Add support for the `callable` builtin

### PR DESCRIPTION
**Pull request by choleraehyq**
Implement the callable as defined here:

* https://docs.python.org/2.7/library/functions.html#callable

`make precommit` passed.

Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

### CODE REVIEW

**Comment by choleraehyq** [comment]
I signed it!

**Comment by choleraehyq** [comment]
@trotterdylan Yeah, `make precommit` passed.

**Comment by trotterdylan** [comment]
Awesome, thanks! Feel free to merge.

**Comment by choleraehyq** [comment]
@trotterdylan Sorry, when will this PR be merged? I have another PR based on this commit.

**Comment by trotterdylan** [comment]
Sorry, I'm new to the GitHub workflow and I thought that approving meant that you were able to merge the change yourself. I'm guessing that's not the case. Would you mind backing out the all/any change for now? I have some separate comments on that we can resolve as a separate PR.

**Comment by S-YOU** [comment]
> Only those with write access to this repository can merge pull requests.

I don't think "you got approved" mean you got write access to repository.

**Comment by choleraehyq** [comment]
I've backoffed the any/all change, that's my fault. All conflicts have been resolved.

I have no permit to merge my PR, because I have only read access; only collaborators and maintainers with write access to this repository can do merge actions.

**Comment by trotterdylan** [comment]
Thanks for getting this done! Everything looks good. Merging now.

**Comment by trotterdylan** [comment]
@choleraehyq By the way, `all()` has been implemented in another PR in the mean time: https://github.com/google/grumpy/blob/master/runtime/builtin_types.go#L193

**Pull request merged**
