### PR TITLE
3rd party additions (from SVN source)

### PR DESCRIPTION
**Pull request by yashpatel5400**
Copied from http://svn.python.org/projects/python/branches/release27-maint/Lib/

### CODE REVIEW

**Comment by corona10** [comment]
@ yashpatel5400 Did you check all 3rd party works well?

**Comment by corona10** [comment]
@yashpatel5400 And you looks like make a separate commit for this PR.

**Comment by corona10** [comment]
I think you need to run tests like this way for your svn copied libraries.

https://github.com/google/grumpy/commit/d641069abd42a11325b2fee05c84ddb88b15a660

**Comment by trotterdylan** [comment]
Please import CPython library sources into third_party/stdlib. Also, as Dong-hee says, everything that's checked into third_party should be confirmed to work. We've been doing this by copying libraries one-by-one from CPython or PyPy.

**Comment by yashpatel5400** [comment]
So, should I create test files for each of the imported libraries and just move these into the stdlib? I didn't put them in stdlib initially because I'd be overwriting files, but I'll move them and do another request.

**Comment by trotterdylan** [comment]
Many of the libraries already exist, so there's no need to import them. I recommend filing separate PRs for each library that you import. E.g. if you want to support mimetypes, then file a PR with mimetypes.py and test/test_mimetypes.py.

**Comment by corona10** [comment]
@yashpatel5400 
To use 3rd party libraries on grumpy needs to implement basic python operation some of them are not implemented yet and some of them are not 100% compatible.

So what you need to do is importIng each of 3rd party library and then run unit tests for them.
Each of unit tests should be worked well on grumpy. If not you should implement related API or modify that API.

**Comment by yashpatel5400** [comment]
Actually,

**Comment by yashpatel5400** [comment]
@corona10 Ah, got it. I'll retract the current push, since it's just all the source files without any tests written for them and start to do separate ones for each

**Pull request closed without merging**
