### PR TITLE
Update .travis.yml to include OS X 

### PR DESCRIPTION
**Pull request by trotterdylan**

### CODE REVIEW

**Comment by S-YOU** [comment]
I think we need this get merge.

**Comment by trotterdylan** [comment]
There's still some issue with pip that I haven't figured out a solution to.

**Comment by S-YOU** [comment]
Ah, right, I do get .functools-lru-cache warning/error at my home computer.

**Comment by trotterdylan** [comment]
I see the .functools-lru-cache messages too but I think it's just a warning. The bigger issue is the pip error `error: must supply either home or prefix/exec-prefix -- not both`. You can see it in the latest travis run [here](https://travis-ci.org/google/grumpy/jobs/191536423).

**Comment by S-YOU** [comment]
Some suggest to do `echo "[install]\nprefix=" > ~/.pydistutils.cfg`, but I am not sure about that.

**Comment by trotterdylan** [comment]
I think I need to make some changes to the way we get and install pylint.

**Pull request closed without merging**
