### PR TITLE
Add commands module

### PR DESCRIPTION
**Pull request by m4ns0ur**

### CODE REVIEW

**Comment by trotterdylan** [comment]
Looks like you need to update the test: replace import_module() calls with a simple `import` statement.

**Comment by trotterdylan** [comment]
Looks like some legit failures now. You can test locally with 

make build/testing/test_commands.pass

**Comment by m4ns0ur** [comment]
@trotterdylan thanks for the tip, I should take a look.

**Comment by m4ns0ur** [comment]
first issue has been addressed on separate PR (#348)

**Comment by m4ns0ur** [comment]
@trotterdylan 2nd and last issue is related to `contextlib` module.
test is not ported for this module, and it needs `sys._getframe` to be implemented first. I'll go through this rabbit hole later.

**Pull request closed without merging**
